set nocompatible
syntax on
filetype on
filetype plugin on
set hlsearch
set showmatch
set matchtime=1
set backspace=indent,eol,start
set cindent
set shiftwidth=2
set tabstop=2
set number 
set wildmenu
set nobackup

